services:
  - type: web
    name: coupon-scoring
    runtime: docker
    dockerfilePath: ./scoring-service/Dockerfile
    dockerContext: ./scoring-service
    region: singapore
    plan: free
    envVars:
      - key: MODEL_DIR
        value: /app/model
      - key: OUTPUTS_DIR
        value: /app/model/outputs

  - type: web
    name: coupon-web
    runtime: docker
    dockerfilePath: ./web/Dockerfile
    dockerContext: ./web
    region: singapore
    plan: free
    envVars:
      - key: SHOPIFY_API_KEY
        value: 0b13ded941fa8b8908df09912d9f18ad
      - key: SHOPIFY_API_SECRET
        value: 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
      - key: SCOPES
        value: read_customers,write_customers,read_orders,read_products,write_discounts,read_discounts
      - key: DATABASE_URL
        value: file:./prisma/prod.db
      - key: SCORING_SERVICE_URL
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
